version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  default: all
  disable:
    - gochecknoglobals
    - gosec
    - funlen
    - varnamelen
    - wrapcheck
    - testpackage
    - err113
    - exhaustruct
    - forbidigo
    - gocognit
    - nestif
    - wsl
    - cyclop
    - gocyclo
    - nlreturn
    - paralleltest
    - ireturn
    - maintidx
    - noctx
    - exhaustive
    - protogetter
    - depguard
    - mnd
    - gomoddirectives
    - nolintlint
    - errcheck
    - funcorder
    - godoclint
    - noinlineerr
    - revive
    - wsl_v5

  settings:
    govet:
      # Don't report about shadowed variables.
      shadow: false
    gofmt:
      # simplify code: gofmt with `-s` option, true by default.
      simplify: true
    whitespace:
      multi-func: true
      multi-if: true
    tagliatelle:
      case:
        rules:
          json: snake
    staticcheck:
      checks: [ "-SA1019" ]
    gomoddirectives:
      replace-allow-list:
        # See go.mod for the explanation why these are needed.
        - google.golang.org/protobuf

  exclusions:
    rules:
      - path: cmd/chantools
        linters:
          - lll
      - path: itest
        linters:
          - dupl
          - thelper
