run:
  # timeout for analysis
  timeout: 4m
  go: "1.23"

linters-settings:
  govet:
    # Don't report about shadowed variables
    shadow: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  whitespace:
    multi-func: true
    multi-if: true
  tagliatelle:
    case:
      rules:
        json: snake
  staticcheck:
    checks: ["-SA1019"]
  gomoddirectives:
    replace-allow-list:
      # See go.mod for the explanation why these are needed.
      - google.golang.org/protobuf


linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gosec
    - funlen
    - varnamelen
    - wrapcheck
    - testpackage
    - err113
    - exhaustruct
    - forbidigo
    - gocognit
    - nestif
    - wsl
    - cyclop
    - gocyclo
    - nlreturn
    - stylecheck
    - paralleltest
    - ireturn
    - maintidx
    - noctx
    - gofumpt
    - exhaustive
    - protogetter
    - depguard
    - mnd
    - gomoddirectives

issues:
  exclude-rules:
    - path: cmd/chantools
      linters:
        - lll
